server:
  port: 9901

spring:
  application:
    name: STUDENT SERVICES
  datasource:
    url: jdbc:postgres://localhost:5433/integrations
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        fomat_sql: true
